In [1]:
from global_vars import *
import numpy as np
import pandas as pd
import gc
import xarray as xr
import os
import glob
from datetime import datetime, timedelta
from tqdm import tqdm
from pathlib import Path
import fastparquet


input_vars = input_vars_ver1
output_vars_t = output_vars_ver1_dtcond
output_vars_q = output_vars_ver1_dcq


src_folder = os.path.join(data_folder, 'nodeep_train_data/')
src_files = glob.glob(os.path.join(src_folder, '*.csv'))

output_folder = os.path.join(data_folder, 'nodeep_train_data_ver1/')


dfs = [pd.read_csv(f) for f in src_files]
big_df = pd.concat(dfs, ignore_index=True).dropna()
big_df

,time,lat,lon,lat.1,lon.1,Tin_lev0,Tin_lev1,Tin_lev2,Tin_lev3,Tin_lev4,...,DCQ_lev48,DCQ_lev49,DCQ_lev50,DCQ_lev51,DCQ_lev52,DCQ_lev53,DCQ_lev54,DCQ_lev55,DCQ_lev56,DCQ_lev57
0,2016-08-09 09:00:00,-89.5,6.5,-89.5,6.5,231.534233,240.616546,239.764657,232.156300,218.942451,...,6.479671e-11,5.684340e-11,4.930042e-11,3.533634e-11,1.722562e-11,-5.069085e-13,-5.022069e-11,-2.135591e-10,-3.582132e-10,-1.395578e-09
1,2016-08-09 09:00:00,-89.5,223.5,-89.5,223.5,231.288278,240.686761,239.781098,231.820017,218.931926,...,7.863009e-10,8.897908e-10,1.062964e-09,1.238316e-09,1.365164e-09,1.400516e-09,1.092471e-09,3.331264e-10,-9.566299e-10,-1.187777e-09
2,2016-08-09 09:00:00,-89.5,106.5,-89.5,106.5,231.148042,240.249383,240.109710,231.646328,219.136626,...,4.105459e-12,4.898085e-12,5.487451e-12,5.931980e-12,4.075232e-12,-4.748318e-12,-2.417941e-11,-9.043003e-11,-9.732974e-10,-5.893574e-10
3,2016-08-09 09:00:00,-89.5,216.5,-89.5,216.5,231.114185,240.822210,239.653774,231.845096,218.952715,...,7.826642e-10,8.754103e-10,1.039529e-09,1.242915e-09,1.367223e-09,1.333148e-09,9.683728e-10,2.636972e-10,-9.247443e-10,-1.306261e-09
4,2016-08-09 09:00:00,-89.5,90.5,-89.5,90.5,231.306535,240.369421,239.917989,231.846031,219.138685,...,2.053182e-11,1.695881e-11,1.879078e-11,1.981616e-11,1.896241e-11,1.366993e-11,-1.588082e-11,-1.037390e-10,-1.190123e-09,-2.007376e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1904395,2020-01-21 03:00:00,89.5,330.5,89.5,330.5,253.280479,237.977858,230.830833,222.515585,212.305040,...,-9.423948e-13,-1.556142e-12,-4.150800e-12,-1.073910e-11,-3.086087e-11,-3.373477e-11,-1.605899e-11,-2.325289e-10,-1.479039e-09,-1.271498e-09
1904396,2020-01-21 03:00:00,89.5,29.5,89.5,29.5,253.320635,238.127589,231.003949,222.779119,212.126292,...,-1.320203e-10,-1.299546e-10,-1.353777e-10,-1.659831e-10,-2.390840e-10,-1.978802e-10,-8.478942e-11,-3.908288e-10,-1.540842e-09,-1.883578e-09
1904397,2020-01-21 03:00:00,89.5,163.5,89.5,163.5,249.527664,238.211793,230.457220,221.920657,213.271263,...,-3.599246e-11,-4.518578e-11,-5.261126e-11,-5.372182e-11,-5.397692e-11,-6.970425e-11,-1.417252e-10,-4.008187e-10,-2.027517e-09,-1.794741e-09
1904398,2020-01-21 03:00:00,89.5,252.5,89.5,252.5,250.154124,238.431674,230.004407,222.672309,212.421851,...,-2.490120e-12,-3.623677e-12,-3.762945e-12,-3.985585e-12,-1.507710e-12,-2.003543e-12,-3.478609e-11,-2.304399e-10,-1.487732e-09,-1.479600e-09
1904399,2020-01-21 03:00:00,89.5,265.5,89.5,265.5,250.782175,238.301252,230.285863,222.397865,212.720946,...,-1.642078e-12,-2.436490e-12,-2.935444e-12,-3.645118e-12,-8.412024e-13,-1.366731e-12,-2.569569e-11,-2.258329e-10,-1.485256e-09,-1.453157e-09

In [2]:
for var in big_df.columns:
    big_df[var] = pd.to_numeric(big_df[var], errors="coerce")


X = big_df[input_vars] ## use just temps for now
y_t = big_df[output_vars_t]
y_q = big_df[output_vars_q]


X.to_parquet(os.path.join(output_folder, "X_train.parquet"),engine="fastparquet")
y_t.to_parquet(os.path.join(output_folder, "y_t_train.parquet"),engine="fastparquet")
y_q.to_parquet(os.path.join(output_folder, "y_q_train.parquet"),engine="fastparquet")

gc.collect()

0

In [3]:
### DO THE SAME FOR TESTING DATA !!!

src_folder = os.path.join(data_folder, 'nodeep_test_data/')
src_files = glob.glob(os.path.join(src_folder, '*.csv'))

output_folder = os.path.join(data_folder, 'nodeep_test_data_ver1/')


dfs = [pd.read_csv(f) for f in src_files]
big_df = pd.concat(dfs, ignore_index=True).dropna()
big_df

,time,lat,lon,lat.1,lon.1,Tin_lev0,Tin_lev1,Tin_lev2,Tin_lev3,Tin_lev4,...,DCQ_lev48,DCQ_lev49,DCQ_lev50,DCQ_lev51,DCQ_lev52,DCQ_lev53,DCQ_lev54,DCQ_lev55,DCQ_lev56,DCQ_lev57
0,2016-09-07 06:00:00,-89.5,0.5,-89.5,0.5,237.541172,240.217251,238.611740,237.990034,236.626039,...,-5.164150e-11,-1.266442e-10,-2.002408e-10,-2.363222e-10,-3.442582e-10,-8.070534e-10,-9.420803e-10,-5.907267e-10,-3.401424e-10,-8.070785e-10
1,2016-09-07 06:00:00,-89.5,1.5,-89.5,1.5,237.401941,240.069716,238.714083,238.013535,236.621995,...,-9.518620e-11,-2.352812e-10,-3.080741e-10,-3.674574e-10,-5.158997e-10,-1.151485e-09,-1.285603e-09,-5.318985e-10,-2.717217e-10,-6.226839e-10
2,2016-09-07 06:00:00,-89.5,2.5,-89.5,2.5,237.419071,240.089683,238.688810,238.035901,236.603954,...,-1.157575e-10,-2.092690e-10,-3.092414e-10,-3.485163e-10,-4.751127e-10,-9.257162e-10,-1.200887e-09,-5.273288e-10,-2.887978e-10,-6.231294e-10
3,2016-09-07 06:00:00,-89.5,3.5,-89.5,3.5,237.406446,240.081052,238.678617,238.066542,236.621333,...,-1.391524e-10,-2.443478e-10,-2.964401e-10,-3.706863e-10,-5.277655e-10,-1.027380e-09,-1.231665e-09,-5.354625e-10,-2.954053e-10,-6.426964e-10
4,2016-09-07 06:00:00,-89.5,4.5,-89.5,4.5,237.445324,240.113462,238.675595,238.045649,236.611534,...,-1.102153e-10,-2.239492e-10,-3.121279e-10,-3.726648e-10,-4.879739e-10,-9.672499e-10,-1.091061e-09,-6.214157e-10,-3.086781e-10,-6.443925e-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138395,2016-09-10 00:00:00,89.5,355.5,89.5,355.5,245.759568,243.593443,234.779150,224.283155,219.338522,...,7.493975e-10,3.291191e-09,4.578583e-10,-2.177439e-09,-9.610298e-10,-8.666363e-10,-6.712121e-10,-1.335188e-09,-4.519458e-09,-3.479854e-10
2138396,2016-09-10 00:00:00,89.5,356.5,89.5,356.5,245.788517,243.616236,234.747157,224.300010,219.348608,...,7.857258e-10,1.261137e-09,4.400409e-10,-2.668725e-09,-8.708795e-10,-3.037750e-10,4.838977e-10,-1.014128e-09,-4.770083e-09,-3.623062e-09
2138397,2016-09-10 00:00:00,89.5,357.5,89.5,357.5,245.760165,243.650567,234.705010,224.332239,219.337100,...,8.185050e-10,5.740625e-10,1.160587e-09,-2.461898e-09,-7.994450e-10,-1.658093e-10,-1.333312e-09,-8.069424e-10,-4.692666e-09,-2.783667e-09
2138398,2016-09-10 00:00:00,89.5,358.5,89.5,358.5,245.782303,243.661720,234.681916,224.347695,219.341214,...,7.229414e-10,1.988420e-10,9.089311e-10,-2.907440e-09,-1.132361e-09,-4.702964e-10,-1.892750e-10,-7.241930e-10,-4.933857e-09,-2.639261e-09
2138399,2016-09-10 00:00:00,89.5,359.5,89.5,359.5,245.533488,243.679145,234.718330,224.343103,219.266148,...,2.323610e-09,8.516036e-09,-2.527424e-09,-1.544593e-09,-1.337617e-09,-6.513605e-10,-7.453337e-10,-2.458988e-09,-4.049050e-09,1.430911e-09

In [4]:
X = big_df[input_vars] ## use just temps for now
y_t = big_df[output_vars_t]
y_q = big_df[output_vars_q]


X.to_parquet(os.path.join(output_folder, "X_test.parquet"),engine="fastparquet")
y_t.to_parquet(os.path.join(output_folder, "y_t_test.parquet"),engine="fastparquet")
y_q.to_parquet(os.path.join(output_folder, "y_q_test.parquet"),engine="fastparquet")

In [5]:
## everything else (lat, lon, date, etc)

test_data_info = big_df.drop(columns=(input_vars+output_vars_t+output_vars_q))
test_data_info.to_parquet(os.path.join(output_folder, "test_info.parquet"),engine="fastparquet")